version: '3.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - vcellnet
    depends_on:
      - rmi

  rmi:
    build:
      context: ./
      dockerfile: Dockerfile-rmi-dev
    environment:
      - rmihost=localhost
      - jmsurl=failover:(tcp://activemq:61616)
      - VIRTUAL_HOST=rmi.local
    secrets:
      - dbpswd
      - jmspswd
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  api:
    build:
      context: ./
      dockerfile: Dockerfile-api-dev
    ports:
      - "8083:8080"
    environment:
      - jmsurl=failover:(tcp://activemq:61616)
    secrets:
      - keystorefile
      - keystorepswd
      - dbpswd
      - jmspswd
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  master:
    build:
      context: ./
      dockerfile: Dockerfile-master-dev
    environment:
      - jmsurl=failover:(tcp://activemq:61616)
    volumes:
      - "./vcelldata:/simdata"
    secrets:
      - dbpswd
      - jmspswd
      - batchuserkeyfile
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - "61619:61616"
    environment:
      - ACTIVEMQ_STATIC_QUEUES=simReq;dataReq;dbreq;simjob;workerevent
      - ACTIVEMQ_STATIC_TOPICS=servicecontrol;daemoncontrol;clientstatus
      - ACTIVEMQ_MIN_MEMORY=1024
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_SCHEDULER=true
    networks:
      - vcellnet
  mongodb:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - vcellnet

networks:
  vcellnet:
secrets:
  dbpswd:
    file: ~/vcellkeys/dbpswd.txt
  jmspswd:
    file: ~/vcellkeys/jmspswd.txt
  keystorepswd:
    file: ~/vcellkeys/keystorepswd.txt
  keystorefile:
    file: ~/vcellkeys/keystore_macbook.jks
  batchuserkeyfile:
    file: ~/.ssh/schaff_rsa