version: '3.1'
services:
  rmi:
    build:
      context: ./
      dockerfile: Dockerfile.rmi
    environment:
      - jmsblob_minsize=10
      - rmihost=155.37.176.21
    secrets:
      - dbpswd
      - jmspswd
    ports:
      - "8088:8088"
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    environment:
      - jmsblob_minsize=10
    secrets:
      - keystorefile
      - keystorepswd
      - dbpswd
      - jmspswd
    ports:
      - "8081:8080"
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  master:
    build:
      context: ./
      dockerfile: Dockerfile.master
    environment:
      - jmsblob_minsize=10
    secrets:
      - dbpswd
      - jmspswd
      - batchuserkeyfile
    volumes:
      - /Volumes/vcell/users:/simdata
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  activemq:
    image: webcenter/activemq:5.14.3
    environment:
      - ACTIVEMQ_STATIC_QUEUES=simReq;dataReq;dbreq;simjob;workerevent
      - ACTIVEMQ_STATIC_TOPICS=servicecontrol;daemoncontrol;clientstatus
      - ACTIVEMQ_MIN_MEMORY=1024
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_SCHEDULER=true
    networks:
      - vcellnet
  mongodb:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    networks:
      - vcellnet
networks:
  vcellnet:
secrets:
  dbpswd:
    file: ~/vcellkeys/dbpswd.txt
  jmspswd:
    file: ~/vcellkeys/jmspswd.txt
  keystorepswd:
    file: ~/vcellkeys/keystorepswd.txt
  keystorefile:
    file: ~/vcellkeys/keystore_macbook.jks
  batchuserkeyfile:
    file: ~/.ssh/schaff_rsa