version: '3.1'
services:
  rmi:
    build:
      context: ./
      dockerfile: Dockerfile-rmi-dev
    ports:
      - "8098:8080"
    environment:
      - rmihost=Jamess-MBP-2.j4home.net
#      - rmihost=Jamess-MacBook-Pro-2.local
  api:
    build:
      context: ./
      dockerfile: Dockerfile-api-dev
    ports:
      - "8081:8080"
  master:
    build:
      context: ./
      dockerfile: Dockerfile-master-dev
    volumes:
      - /Users/schaff/Documents/workspace-modular/vcell/sandbox:/simdata
#      - /Volumes/vcell/users:/simdata
  activemq:
    image: webcenter/activemq:5.14.3
    ports: 
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
  mongodb:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"

