version: '3'
services:
  rmi:
    ports:
      - "8088:8080"
    environment:
      - rmihost=vcell-rmi-alpha.cam.uchc.edu
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vcell-rmi-alpha.cam.uchc.edu
          - node.label == DMZ
          - node.label != INTERNAL
  api:
    ports:
      - "8081:8080"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vcellapi.cam.uchc.edu
          - node.label == DMZ
          - node.label != INTERNAL
  master:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != vcellapi.cam.uchc.edu
          - node.hostname != vcell-rmi-alpha.cam.uchc.edu
          - node.hostname != vcell-rmi-beta.cam.uchc.edu
          - node.hostname != vcell-rmi-rel.cam.uchc.edu
          - node.label != DMZ
          - node.label == INTERNAL
  activemq:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != vcell-docker.cam.uchc.edu
          - node.label != DMZ
          - node.label == INTERNAL
  mongodb:
    deploy:
      mode: replicated
      replicas: 1

