version: '3.1'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile-api-dev
    environment:
      - jmsuser=clientUser
      - jmsurl=failover:(tcp://activemq:61616)
    ports:
      - "8083:8080"
      - "8013:8000" # java remote debugging
    secrets:
      - keystorefile
      - keystorepswd
      - dbpswd
      - jmspswd
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  master:
    build:
      context: ./
      dockerfile: Dockerfile-master-dev
    environment:
      - jmsuser=clientUser
      - jmsurl=failover:(tcp://activemq:61616)
      - simdatadir_external=/share/apps/vcell3/users/
      - htclogdir_external=/share/apps/vcell3/htclogs/
      - singularity_imagefile=/share/apps/vcell3/singularity/vcell-batch-remoting.img
      - docker_name=schaff/vcell-batch:remoting
    ports:
      - "8023:8000" # java remote debugging
    volumes:
      - "/Volumes/vcell/users:/simdata"
    secrets:
      - dbpswd
      - jmspswd
      - batchuserkeyfile
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - "8161:8161"
      - "61619:61616"
    environment:
      - ACTIVEMQ_STATIC_QUEUES=simReq;dataReq;dbreq;simjob;workerevent
      - ACTIVEMQ_STATIC_TOPICS=servicecontrol;daemoncontrol;clientstatus
      - ACTIVEMQ_MIN_MEMORY=1024
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_USERS_clientUser=dummy
      - ACTIVEMQ_GROUPS_reads=clientUser
      - ACTIVEMQ_GROUPS_writes=clientUser
      - ACTIVEMQ_CONFIG_AUTHENABLED=true
    networks:
      - vcellnet
  mongodb:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - vcellnet

networks:
  vcellnet:
secrets:
  dbpswd:
    file: ~/vcellkeys/dbpswd.txt
  jmspswd:
    file: ~/vcellkeys/jmspswd.txt
  keystorepswd:
    file: ~/vcellkeys/keystorepswd.txt
  keystorefile:
    file: ~/vcellkeys/keystore_macbook.jks
  batchuserkeyfile:
    file: ~/.ssh/schaff_rsa