apiVersion: v1
kind: Service
metadata:
  name: activemqsim
  labels:
    app: activemqsim
    dist: rel
spec:
  type: NodePort
  ports:
    - name: activemqsim-amq
      port: 61616
      nodePort: 30616
      protocol: TCP
    - name: activemqsim-http
      port: 8161
      nodePort: 30161
      protocol: TCP
  selector:
    app: activemqsim
    dist: rel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: activemqsim
    dist: rel
  name: activemqsim
spec:
  selector:
    matchLabels:
      app: activemqsim
      dist: rel
  replicas: 1
  template:
    metadata:
      labels:
        app: activemqsim
        dist: rel
    spec:
      containers:
      - env:
        - name: ACTIVEMQ_CONFIG_AUTHENABLED
          value: "true"
        - name: ACTIVEMQ_ENABLED_SCHEDULER
          value: "true"
        - name: ACTIVEMQ_GROUPS_reads
          value: clientUser
        - name: ACTIVEMQ_GROUPS_writes
          value: clientUser
        - name: ACTIVEMQ_MAX_MEMORY
          value: "2048"
        - name: ACTIVEMQ_MIN_MEMORY
          value: "512"
        - name: ACTIVEMQ_STATIC_QUEUES
          value: workerEvent
        - name: ACTIVEMQ_STATIC_TOPICS
          value: serviceControl
        - name: ACTIVEMQ_USERS_clientUser
          value: dummy
        image: webcenter/activemq:5.14.3
        name: activemqsim
        ports:
        - containerPort: 61616
        - containerPort: 8161
        resources:
          limits:
            memory: 2097152e3
          requests:
            memory: 1048576e3
      restartPolicy: Always