apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose-simple.yml convert
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: data
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose-simple.yml convert
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data
    spec:
      containers:
      - env:
        - name: export_baseurl
        - name: jmshost_int_internal
          value: activemqint
        - name: jmsport_int_internal
          value: "61616"
        - name: jmsuser
          value: clientUser
        - name: mongodb_database
          value: test
        - name: mongodb_host_internal
          value: mongodb
        - name: mongodb_port_internal
          value: "27017"
        - name: serverid
        - name: servertype
          value: CombinedData
        - name: simdataCacheSize
          value: "10000000"
        - name: softwareVersion
        image: '/vcell-data:'
        name: data
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 3145728e3
          requests:
            memory: 3145728e3
        volumeMounts:
        - mountPath: /simdata
          name: data-claim0
        - mountPath: /htclogs
          name: data-claim1
      restartPolicy: Always
      volumes:
      - name: data-claim0
        persistentVolumeClaim:
          claimName: data-claim0
      - name: data-claim1
        persistentVolumeClaim:
          claimName: data-claim1
status: {}
