apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: data-claim0
  name: nfs-simdata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
