version: '3.1'
services:
  api:
    image: schaff/vcell-api:${VCELL_TAG}
    environment:
      - softwareVersion=${VCELL_VERSION}
      - serverid=${VCELL_SITE}
      - jmsuser=clientUser
      - jmsurl=failover:(tcp://activemq:61616)
    ports:
      - "${VCELL_APIPORT}:8080"
      - "8000" # java remote debugging
    secrets:
      - keystorefile
      - keystorepswd
      - dbpswd
      - jmspswd
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
    deploy:
      mode: replicated
      replicas: 1
  master:
    image: schaff/vcell-master:${VCELL_TAG}
    environment:
      - softwareVersion=${VCELL_VERSION}
      - serverid=${VCELL_SITE}
      - jmsuser=clientUser
      - jmsurl=failover:(tcp://activemq:61616)
      - simdatadir_external=${VCELL_SIMDATADIR_EXTERNAL}
      - htclogdir_external=${VCELL_HTCLOGS_EXTERNAL}
      - singularity_imagefile=${VCELL_SINGULARITY_EXTERNAL}/vcell-batch-${VCELL_TAG}.img
      - docker_name=schaff/vcell-batch:${VCELL_TAG}
    ports:
      - "8000" # java remote debugging
    volumes:
      - "${VCELL_SIMDATADIR_HOST}:/simdata"
    secrets:
      - dbpswd
      - jmspswd
      - batchuserkeyfile
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.zone == INTERNAL
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - "${VCELL_JMSPORT}:61616"
      - "${VCELL_JMSRESTPORT}:8161"
    environment:
      - ACTIVEMQ_STATIC_QUEUES=simReq;dataReq;dbreq;simjob;workerevent
      - ACTIVEMQ_STATIC_TOPICS=servicecontrol;daemoncontrol;clientstatus
      - ACTIVEMQ_MIN_MEMORY=1024
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_USERS_clientUser=dummy
      - ACTIVEMQ_GROUPS_reads=clientUser
      - ACTIVEMQ_GROUPS_writes=clientUser
      - ACTIVEMQ_CONFIG_AUTHENABLED=true
    networks:
      - vcellnet
    deploy:
      mode: replicated
      replicas: 1
  mongodb:
    image: schaff/vcell-mongo:${VCELL_TAG}
    ports:
      - "${VCELL_MONGOPORT}:27017"
    networks:
      - vcellnet
    deploy:
      mode: replicated
      replicas: 1

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - vcellnet

networks:
  vcellnet:
secrets:
  dbpswd:
    file: ${VCELL_SECRETS_DIR}/dbpswd.txt
  jmspswd:
    file: ${VCELL_SECRETS_DIR}/jmspswd.txt
  keystorepswd:
    file: ${VCELL_SECRETS_DIR}/keystorepswd.txt
  keystorefile:
    file: ${VCELL_SECRETS_DIR}/keystore.jks
  batchuserkeyfile:
    file: ${VCELL_SECRETS_DIR}/schaff_rsa
