version: '3.1'
services:
  clientgen:
    image: "${VCELL_REPO_NAMESPACE}/vcell-clientgen:${VCELL_TAG}"
    environment:
      - compiler_updateSiteBaseUrl=$VCELL_UPDATE_SITE
      - compiler_Site=$VCELL_SITE_CAMEL
      - compiler_vcellVersion=$VCELL_VERSION_NUMBER
      - compiler_vcellBuild=$VCELL_BUILD_NUMBER
      - compiler_softwareVersionString=$VCELL_VERSION
      - compiler_rmiHosts=${VCELL_API_HOST_EXTERNAL}:$VCELL_API_PORT_EXTERNAL
      - compiler_bioformatsJarFile=$VCELL_BIOFORMATS_JAR_FILE
      - compiler_bioformatsJarDownloadURL=$VCELL_BIOFORMATS_JAR_URL
      - compiler_applicationId=$VCELL_CLIENT_APPID
      - macJre=$VCELL_INSTALLER_JRE_MAC
      - win64Jre=$VCELL_INSTALLER_JRE_WIN64
      - win32Jre=$VCELL_INSTALLER_JRE_WIN32
      - linux64Jre=$VCELL_INSTALLER_JRE_LINUX64
      - linux32Jre=$VCELL_INSTALLER_JRE_LINUX32
    volumes:
      #
      # Java JRE archive files for inclusion in the installed VCell Client (mapped to /jres folder in Docker container)
      #    macosx-amd64-1.8.0_141
      #    windows-amd64-1.8.0_141
      #    windows-x86-1.8.0_141
      #
      - "$HOME/.install4j6/jres:/jres"
      - "./generated_installers:/outputdir"
    secrets:
      - winCodeSignKeystore_pfx
      - winCodeSignKeystore_pswdfile
      - macCodeSignKeystore_p12
      - macCodeSignKeystore_pswdfile
      - Install4J_product_key_file
secrets:
  #
  # simple and slightly secure way of handling credentials (if file permissions are locked down)
  # even better if using a proper 'secrets' management infrastructure like Vault 
  # (https://www.vaultproject.io/community.html).
  #
  winCodeSignKeystore_pfx:
    file: "${VCELL_DEPLOY_SECRETS_DIR}/VCELL_UCONN_MS_2017.pfx"
  winCodeSignKeystore_pswdfile:
    file: "${VCELL_DEPLOY_SECRETS_DIR}/VCELL_UCONN_MS_2017_pswd.txt"
  macCodeSignKeystore_p12:
    file: "${VCELL_DEPLOY_SECRETS_DIR}/VCELL_APPLE_2015.p12"
  macCodeSignKeystore_pswdfile:
    file: "${VCELL_DEPLOY_SECRETS_DIR}/VCELL_APPLE_2015_pswd.txt"
  Install4J_product_key_file:
    file: "${VCELL_DEPLOY_SECRETS_DIR}/Install4J_product_key.txt"
