version: '3.1'
services:
  api:
    deploy:
      mode: replicated
      replicas: 1
  master:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.zone == INTERNAL
  activemq:
    deploy:
      mode: replicated
      replicas: 1
  mongodb:
    deploy:
      mode: replicated
      replicas: 1

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - vcellnet
