version: '3.1'
services:
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - "61617:61616"
      - "8162:8161"
    environment:
      - ACTIVEMQ_STATIC_QUEUES=simReq;dataReq;dbReq;simJob;workerEvent
      - ACTIVEMQ_STATIC_TOPICS=serviceControl;daemonControl;clientStatus
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_USERS_clientUser=dummy
      - ACTIVEMQ_GROUPS_reads=clientUser
      - ACTIVEMQ_GROUPS_writes=clientUser
      - ACTIVEMQ_CONFIG_AUTHENABLED=true
    networks:
      - vcellnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vcell-docker
      resources:
        limits:
          cpus: '0.50'
          memory: 2500M
        reservations:
          cpus: '0.25'
          memory: 600M
  mongodb:
    image: schaff/vcell-mongo:latest
    ports:
      - "27018:27017"
    networks:
      - vcellnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vcell-docker
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 50M
      
networks:
  vcellnet:
