name: CI-application-containers

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Install Singularity # to make singularity image for cluster
      uses: eWaterCycle/setup-singularity@v6
      with:
        singularity-version: 3.7.1$VCELL_REPO_NAMESPACE/vcel
    - name: build and publish all images
      shell: bash
      run: |
        cd docker/build
        export VCELL_TAG=`git rev-parse HEAD | cut -c -7`
        export VCELL_REPO_NAMESPACE=ghcr.io/virtualcell
        sudo docker login -u moraru -p ${{ secrets.TEST }} ghcr.io
        docker login -u moraru -p ${{ secrets.TEST }} ghcr.io
        ./build.sh all $VCELL_REPO_NAMESPACE $VCELL_TAG
        cd singularity-vm
        singularity remote login -u moraru -p ${{ secrets.TEST }} ghcr.io
    - name: tag as latest
      shell: bash
      run: |
        docker tag $VCELL_REPO_NAMESPACE/vcell-web:$VCELL_TAG $VCELL_REPO_NAMESPACE/vcell-web:latest
        docker push --all-tags $VCELL_REPO_NAMESPACE/vcell
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
