name: CI-application-containers

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set global environment variables
      run: |
        echo "VCELL_TAG=`git rev-parse HEAD | cut -c -7`" >> $GITHUB_ENV
        echo "VCELL_REPO_NAMESPACE=ghcr.io/virtualcell" >> $GITHUB_ENV
    - name: setup java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Install Singularity # to make singularity image for cluster
      uses: eWaterCycle/setup-singularity@v6
      with:
        singularity-version: 3.7.1
    - name: build and publish all images
      shell: bash
      run: |
        cd docker/build
        sudo docker login -u moraru -p ${{ secrets.TEST }} ghcr.io
        docker login -u moraru -p ${{ secrets.TEST }} ghcr.io
        ./build.sh all ${{ env.VCELL_REPO_NAMESPACE }} ${{ env.VCELL_TAG }}
        cd singularity-vm
        singularity remote login -u moraru -p ${{ secrets.TEST }} oras://ghcr.io
    - name: tag as latest and push to registry
      shell: bash
      run: |
        for CONTAINER in vcell-api vcell-batch vcell-clientgen vcell-data vcell-db vcell-mongo vcell-sched vcell-submit vcell-web
        do 
          docker tag ${{ env.VCELL_REPO_NAMESPACE }}/$CONTAINER:${{ env.VCELL_TAG }} ${{ env.VCELL_REPO_NAMESPACE }}/$CONTAINER:latest
        done
        docker push --all-tags ${{ env.VCELL_REPO_NAMESPACE }}
        cd docker/build/singularity-vm
        echo singularity push -U $(ls *img) ${{ env.VCELL_REPO_NAMESPACE }}/vcell-batch-singularity:${{ env.VCELL_TAG }}
        
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
