name: Debug test

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'version'     
        required: true
        default: '7.4.0.24'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: insert version
      run: |
        set -ux
        sed -i 's/_VC_VERSION_TAG_/${{ github.event.inputs.tag_name }}/g' biosimulators.json
        cat biosimulators.json | head
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: https://uploads.github.com/repos/virtualcell/vcell/releases/${{ github.event.inputs.tag_name }}
        asset_path: biosimulators.json
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
