name: Build and Test the Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract JDK and maven Tarball
        run: |
          wget https://www.dropbox.com/s/h70d7erl2mkufbk/jdk-8u241-linux-x64.tar.gz?dl=1
          tar -xvzf jdk-8u241-linux-x64.tar.gz?dl=1
          mv jdk1.8.0_241 jdk
          wget http://mirrors.advancedhosters.com/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -xvzf apache-maven-3.6.3-bin.tar.gz
          mv apache-maven-3.6.3 maven
      - name: Export Environment variables for compiling and install dependencies 
        run: |
          export JAVA_HOME=`pwd`/jdk
          export PATH=${JAVA_HOME}/bin:${PATH}
          echo $JAVA_HOME
          java -version
          export M2_HOME=`pwd`/maven
          export PATH=${M2_HOME}/bin:${PATH}
          mvn -version
          java -version
          echo "#################################"
          echo "#### Installing dependencies ####"
          echo "#################################"
          mvn clean install dependency:copy-dependencies
      - name: Buid and test the docker image
        env:
          JOB_ID: ${{secrets.JOB_ID}}
          SIMULATION_ID: ${{secrets.SIMULATION_ID}}
          AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
          AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
          AUTH0_BIOSIMULATIONS_AUDIENCE: ${{secrets.AUTH0_BIOSIMULATIONS_AUDIENCE}}
          AUTH0_TOKEN_URL: ${{secrets.AUTH0_TOKEN_URL}}
          AUTH0_GRANT_TYPE: ${{secrets.AUTH0_GRANT_TYPE}}
          JOBHOOK_URL: ${{secrets.JOBHOOK_URL}}
        run: |  
          echo "===> Building docker image <==="
          docker build --file docker/build/Dockerfile-sedml-solver --tag crbm/biosimulations_vcell_api:latest .
          echo "===> Testing the docker image <==="
          docker run -v `pwd`/sample_model:/usr/local/app/vcell/simulation -e JOB_ID -e SIMULATION_ID -e AUTH0_CLIENT_ID -e AUTH0_CLIENT_SECRET -e AUTH0_BIOSIMULATIONS_AUDIENCE -e AUTH0_TOKEN_URL -e AUTH0_GRANT_TYPE -e JOBHOOK_URL crbm/biosimulations_vcell_api:latest
      - name: List all files from sample_model directory
        run: ls `pwd`/sample_model/out/sample_tsk_0_0
