name: Build the Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract JDK and maven Tarball
        run: |
          wget https://vcell.org/webstart/pipeline_files/jdk-8u241-linux-x64.tar.gz
          tar -xvzf jdk-8u241-linux-x64.tar.gz
          mv jdk1.8.0_241 jdk
          wget https://vcell.org/webstart/pipeline_files/apache-maven-3.6.3-bin.tar.gz
          tar -xvzf apache-maven-3.6.3-bin.tar.gz
          mv apache-maven-3.6.3 maven
      - name: Install dependencies
        run: |
          export JAVA_HOME=`pwd`/jdk
          export PATH=${JAVA_HOME}/bin:${PATH}
          echo $JAVA_HOME
          java -version
          export M2_HOME=`pwd`/maven
          export PATH=${M2_HOME}/bin:${PATH}
          mvn -version
          java -version
          echo "#################################"
          echo "#### Installing dependencies ####"
          echo "#################################"
          mvn clean install dependency:copy-dependencies
          docker build --file docker/build/Dockerfile-vcell-cli \
                    	--tag biosimulators_vcell:7.3.0.0 .
      - name: Run the Docker image with test files
        run: |
          docker run \
              --tty \
              --rm \
              --mount type=bind,source="$(pwd)"/tests/fixtures,target=/root/in,readonly \
              --mount type=bind,source="$(pwd)"/tests/results,target=/root/out \
              biosimulators_vcell:7.3.0.0 \
                -i /root/in/BIOMD0000000823.omex \
                -o /root/out