#name: Windows mvn Installation
#on: [push, pull_request]
#jobs:
#  build:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#      - name: Publish to GitHub Packages
#        run: mvn clean install dependency:copy-dependencies
